[2024-09-22T12:57:25.819+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T12:57:25.826+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project.wait_for_api manual__2024-09-22T12:57:24.010523+00:00 [queued]>
[2024-09-22T12:57:25.829+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project.wait_for_api manual__2024-09-22T12:57:24.010523+00:00 [queued]>
[2024-09-22T12:57:25.829+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-22T12:57:25.834+0000] {taskinstance.py:2888} INFO - Executing <Task(HttpSensor): wait_for_api> on 2024-09-22 12:57:24.010523+00:00
[2024-09-22T12:57:25.837+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5354) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T12:57:25.838+0000] {standard_task_runner.py:72} INFO - Started process 5356 to run task
[2024-09-22T12:57:25.839+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'project', 'wait_for_api', 'manual__2024-09-22T12:57:24.010523+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/project.py', '--cfg-path', '/tmp/tmp74r4xur_']
[2024-09-22T12:57:25.839+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask wait_for_api
[2024-09-22T12:57:25.860+0000] {task_command.py:467} INFO - Running <TaskInstance: project.wait_for_api manual__2024-09-22T12:57:24.010523+00:00 [running]> on host 0bbd6d2129ab
[2024-09-22T12:57:25.894+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='project' AIRFLOW_CTX_TASK_ID='wait_for_api' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T12:57:24.010523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T12:57:24.010523+00:00'
[2024-09-22T12:57:25.895+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-22T12:57:25.895+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-22T12:57:25.895+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_api state:running start_date:2024-09-22 12:57:25.826460+00:00
[2024-09-22T12:57:25.895+0000] {logging_mixin.py:190} INFO - Dag name:project and current dag run status:running
[2024-09-22T12:57:25.895+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T12:57:25.896+0000] {baseoperator.py:405} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-09-22T12:57:25.896+0000] {http.py:137} INFO - Poking: api/
[2024-09-22T12:57:25.900+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2024-09-22T12:57:26.297+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 149, in poke
    return self.response_check(response, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/project.py", line 20, in <lambda>
    response_check=lambda response: response.statuscode==200,
                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'statuscode'. Did you mean: 'status_code'?
[2024-09-22T12:57:26.308+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-22T12:57:26.308+0000] {logging_mixin.py:190} INFO - Task start:2024-09-22 12:57:25.826460+00:00 end:2024-09-22 12:57:26.307904+00:00 duration:0.481444
[2024-09-22T12:57:26.309+0000] {logging_mixin.py:190} INFO - Task:<Task(HttpSensor): wait_for_api> dag:<DAG: project> dagrun:<DagRun project @ 2024-09-22 12:57:24.010523+00:00: manual__2024-09-22T12:57:24.010523+00:00, state:running, queued_at: 2024-09-22 12:57:24.031198+00:00. externally triggered: True>
[2024-09-22T12:57:26.309+0000] {logging_mixin.py:190} INFO - Failure caused by 'Response' object has no attribute 'statuscode'
[2024-09-22T12:57:26.309+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=project, task_id=wait_for_api, run_id=manual__2024-09-22T12:57:24.010523+00:00, execution_date=20240922T125724, start_date=20240922T125725, end_date=20240922T125726
[2024-09-22T12:57:26.323+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T12:57:26.324+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task wait_for_api ('Response' object has no attribute 'statuscode'; 5356)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 149, in poke
    return self.response_check(response, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/project.py", line 20, in <lambda>
    response_check=lambda response: response.statuscode==200,
                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'statuscode'. Did you mean: 'status_code'?
[2024-09-22T12:57:26.360+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-22T12:57:26.373+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T12:57:26.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
